// Package sshconf owns the per-session SSH config files under
// ~/.ssh/config.d, the Include line in ~/.ssh/config, and the RDE-only
// known_hosts file.
//
// Every file this package writes starts with a marker line naming the
// session. Files without that marker are never modified or deleted.
package sshconf

import (
	"bufio"
	"context"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

const markerPrefix = "# managed by bitrise :herdr; session="

// ErrUnmanaged is returned when a file exists at an entry's path but this
// plugin didn't create it.
var ErrUnmanaged = errors.New("file exists and is not managed by bitrise :herdr")

type Paths struct {
	Home       string
	ConfigFile string // ~/.ssh/config
	Dir        string // ~/.ssh/config.d
	KnownHosts string // ~/.ssh/known_hosts_rde
}

func DefaultPaths(home string) Paths {
	return Paths{
		Home:       home,
		ConfigFile: filepath.Join(home, ".ssh", "config"),
		Dir:        filepath.Join(home, ".ssh", "config.d"),
		KnownHosts: filepath.Join(home, ".ssh", "known_hosts_rde"),
	}
}

// Entry is one session's SSH host block.
type Entry struct {
	Alias        string
	SessionID    string
	HostName     string
	Port         int
	User         string
	IdentityFile string // optional
}

func (p Paths) path(alias string) string { return filepath.Join(p.Dir, alias) }

// Render returns the file contents for an entry. Paths are absolute, because
// ssh expands ~ from the passwd entry, not $HOME.
func (p Paths) Render(e Entry) string {
	var b strings.Builder
	fmt.Fprintf(&b, "%s%s\n", markerPrefix, e.SessionID)
	b.WriteString("# Generated by `bitrise :herdr`. Edits are overwritten on the next sync.\n")
	fmt.Fprintf(&b, "Host %s\n", e.Alias)
	fmt.Fprintf(&b, "  HostName %s\n", e.HostName)
	fmt.Fprintf(&b, "  Port %d\n", e.Port)
	fmt.Fprintf(&b, "  User %s\n", e.User)
	if e.IdentityFile != "" {
		fmt.Fprintf(&b, "  IdentityFile %s\n", quote(e.IdentityFile))
	}
	fmt.Fprintf(&b, "  UserKnownHostsFile %s\n", quote(p.KnownHosts))
	b.WriteString("  StrictHostKeyChecking accept-new\n")
	b.WriteString("  ServerAliveInterval 30\n")
	return b.String()
}

func quote(s string) string {
	if strings.ContainsAny(s, " \t") {
		return `"` + s + `"`
	}
	return s
}

// Scan returns the managed entries whose alias starts with prefix, keyed by
// alias, and the aliases of files that match the prefix but have no marker.
func (p Paths) Scan(prefix string) (managed map[string]Entry, unmanaged map[string]bool, err error) {
	managed = map[string]Entry{}
	unmanaged = map[string]bool{}
	des, err := os.ReadDir(p.Dir)
	if errors.Is(err, fs.ErrNotExist) {
		return managed, unmanaged, nil
	}
	if err != nil {
		return nil, nil, err
	}
	for _, de := range des {
		name := de.Name()
		if !de.Type().IsRegular() || !strings.HasPrefix(name, prefix) || strings.HasPrefix(name, ".") {
			continue
		}
		data, err := os.ReadFile(filepath.Join(p.Dir, name))
		if err != nil {
			return nil, nil, err
		}
		e, ok := parse(string(data))
		if !ok || e.Alias != name {
			unmanaged[name] = true
			continue
		}
		managed[name] = e
	}
	return managed, unmanaged, nil
}

func parse(data string) (Entry, bool) {
	sc := bufio.NewScanner(strings.NewReader(data))
	if !sc.Scan() || !strings.HasPrefix(sc.Text(), markerPrefix) {
		return Entry{}, false
	}
	e := Entry{SessionID: strings.TrimSpace(strings.TrimPrefix(sc.Text(), markerPrefix))}
	for sc.Scan() {
		f := strings.Fields(sc.Text())
		if len(f) < 2 {
			continue
		}
		val := strings.Trim(strings.Join(f[1:], " "), `"`)
		switch strings.ToLower(f[0]) {
		case "host":
			e.Alias = val
		case "hostname":
			e.HostName = val
		case "port":
			e.Port, _ = strconv.Atoi(val)
		case "user":
			e.User = val
		case "identityfile":
			e.IdentityFile = val
		}
	}
	return e, e.SessionID != "" && e.Alias != ""
}

// Write creates or replaces an entry's file atomically with mode 0600. It
// reports whether the file changed. It refuses to replace an unmanaged file.
func (p Paths) Write(e Entry) (bool, error) {
	want := p.Render(e)
	path := p.path(e.Alias)
	if cur, err := os.ReadFile(path); err == nil {
		if _, ok := parse(string(cur)); !ok {
			return false, fmt.Errorf("%s: %w", path, ErrUnmanaged)
		}
		if string(cur) == want {
			return false, nil
		}
	} else if !errors.Is(err, fs.ErrNotExist) {
		return false, err
	}
	if err := os.MkdirAll(p.Dir, 0o700); err != nil {
		return false, err
	}
	return true, writeAtomic(path, []byte(want), 0o600)
}

// Remove deletes an entry's file if this plugin created it.
func (p Paths) Remove(alias string) error {
	path := p.path(alias)
	data, err := os.ReadFile(path)
	if errors.Is(err, fs.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	if _, ok := parse(string(data)); !ok {
		return fmt.Errorf("%s: %w", path, ErrUnmanaged)
	}
	return os.Remove(path)
}

// IncludePattern is the glob the Include line in ~/.ssh/config points at.
func (p Paths) IncludePattern(prefix string) string {
	return filepath.Join(p.Dir, prefix+"*")
}

// EnsureInclude makes sure ~/.ssh/config includes the managed files before
// its first Host or Match block. An Include placed after a block is silently
// scoped to that block, so a misplaced line is moved to the top. The file is
// created if absent and backed up once before the first edit. With dryRun it
// only reports whether a change is needed.
func (p Paths) EnsureInclude(prefix string, dryRun bool) (bool, error) {
	pattern := p.IncludePattern(prefix)
	data, err := os.ReadFile(p.ConfigFile)
	exists := err == nil
	if err != nil && !errors.Is(err, fs.ErrNotExist) {
		return false, err
	}
	lines := strings.SplitAfter(string(data), "\n")
	if len(lines) > 0 && lines[len(lines)-1] == "" {
		lines = lines[:len(lines)-1]
	}

	firstBlock := len(lines)
	found := -1
	for i, l := range lines {
		f := strings.Fields(l)
		if len(f) == 0 || strings.HasPrefix(f[0], "#") {
			continue
		}
		kw := strings.ToLower(strings.SplitN(f[0], "=", 2)[0])
		if (kw == "host" || kw == "match") && firstBlock == len(lines) {
			firstBlock = i
		}
		if kw == "include" && found < 0 {
			for _, arg := range f[1:] {
				if p.samePath(strings.Trim(arg, `"`), pattern) {
					found = i
				}
			}
		}
	}
	if found >= 0 && found < firstBlock {
		return false, nil
	}
	if dryRun {
		return true, nil
	}

	if found >= 0 {
		// Drop our pattern from the misplaced line, and the line itself if
		// nothing else is left on it.
		f := strings.Fields(lines[found])
		var rest []string
		for _, arg := range f[1:] {
			if !p.samePath(strings.Trim(arg, `"`), pattern) {
				rest = append(rest, arg)
			}
		}
		if len(rest) == 0 {
			lines = append(lines[:found], lines[found+1:]...)
		} else {
			lines[found] = f[0] + " " + strings.Join(rest, " ") + "\n"
		}
	}
	out := "# Added by `bitrise :herdr`. Must stay above every Host block.\n" +
		"Include " + quote(pattern) + "\n"
	if len(lines) > 0 {
		out += "\n" + strings.Join(lines, "")
	}

	mode := fs.FileMode(0o600)
	if exists {
		if st, err := os.Stat(p.ConfigFile); err == nil {
			mode = st.Mode().Perm()
		}
		backup := p.ConfigFile + ".bak-bitrise-herdr"
		if _, err := os.Stat(backup); errors.Is(err, fs.ErrNotExist) {
			if err := os.WriteFile(backup, data, 0o600); err != nil {
				return false, fmt.Errorf("back up %s: %w", p.ConfigFile, err)
			}
		}
	} else if err := os.MkdirAll(filepath.Dir(p.ConfigFile), 0o700); err != nil {
		return false, err
	}

	// Write through a symlink (dotfiles repos, home-manager) instead of
	// replacing the link with a plain file.
	target := p.ConfigFile
	if exists {
		if target, err = filepath.EvalSymlinks(p.ConfigFile); err != nil {
			return false, err
		}
	}
	if err := writeAtomic(target, []byte(out), mode); err != nil {
		if target != p.ConfigFile {
			return false, fmt.Errorf("%s is a symlink to %s, which couldn't be updated (%w); add this line above every Host block yourself:\n  Include %s",
				p.ConfigFile, target, err, quote(pattern))
		}
		return false, err
	}
	return true, nil
}

func (p Paths) samePath(a, b string) bool {
	expand := func(s string) string {
		if strings.HasPrefix(s, "~/") {
			s = filepath.Join(p.Home, s[2:])
		}
		return filepath.Clean(s)
	}
	return expand(a) == expand(b)
}

// RemoveHostKey drops a host's key from the RDE known_hosts file. It's a
// no-op if the file doesn't exist.
func (p Paths) RemoveHostKey(ctx context.Context, host string, port int) error {
	if _, err := os.Stat(p.KnownHosts); errors.Is(err, fs.ErrNotExist) {
		return nil
	}
	name := host
	if port != 22 {
		name = fmt.Sprintf("[%s]:%d", host, port)
	}
	out, err := exec.CommandContext(ctx, "ssh-keygen", "-R", name, "-f", p.KnownHosts).CombinedOutput()
	if err != nil {
		return fmt.Errorf("ssh-keygen -R %s: %w: %s", name, err, strings.TrimSpace(string(out)))
	}
	// ssh-keygen leaves a .old copy next to the file; it holds only RDE keys.
	_ = os.Remove(p.KnownHosts + ".old")
	return nil
}

func writeAtomic(path string, data []byte, mode fs.FileMode) error {
	tmp, err := os.CreateTemp(filepath.Dir(path), "."+filepath.Base(path)+".tmp-*")
	if err != nil {
		return err
	}
	defer os.Remove(tmp.Name())
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Chmod(mode); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmp.Name(), path)
}

// SortedAliases returns map keys in order, for stable output.
func SortedAliases[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
